### ISSUE TITLE
运行有问题，会闪退

### ISSUE THREAD

**Issue by lanming-pan** [abeelan/jdSeckill#3]

**Comment by abeelan** [comment]
具体的报错信息有吗？

**Comment by lanming-pan** [comment]
File\"F: jdseckill-main Nmain
line 1. in <module
g
File \"F: \\idseckill-main\\logger. py\", line 32, in <module
)
File \" F: \\ijaseckill-main \\logger. py, line 27. in set
Lename
D, interval=1, backupCount=5, encoding=utf-8
File D: \\python\\lib\\logging \\handlers. py, line 199. in -init
encoding, delay)
File D: \\python 37\\lib\\logging \\handlers. py, line 54. in
pigging. FileHandler__<self, filename. mode, encoding, delay)
Le \"D: \\python 37\\lib\\logg
line 1041, infinit
Streamhand
n()
py, line 1070. in _open
turn open (self. base Filename, self mode, encoding=selfencoding>
FileNotFoundError: [Errno 2] No such file or directory: F:\\jdseckill-main \\\\log
Soutput

**Comment by angelshadow** [comment]
> File"F: jdseckill-main Nmain
> line 1. in <module
> g
> File "F: \idseckill-main\logger. py", line 32, in <module
> )
> File " F: \ijaseckill-main \logger. py, line 27. in set
> Lename
> D, interval=1, backupCount=5, encoding=utf-8
> File D: \python\lib\logging \handlers. py, line 199. in -init
> encoding, delay)
> File D: \python 37\lib\logging \handlers. py, line 54. in
> pigging. FileHandler__<self, filename. mode, encoding, delay)
> Le "D: \python 37\lib\logg
> line 1041, infinit
> Streamhand
> n()
> py, line 1070. in _open
> turn open (self. base Filename, self mode, encoding=selfencoding>
> FileNotFoundError: [Errno 2] No such file or directory: F:\jdseckill-main \\log
> Soutput

没有log目录，自己建一个就OK了

**Comment by abeelan** [comment]
这个目录判断没有会自动创建，我在 mac 系统上没有出现问题，windows 没有机器测试。
2.1 日起，京东关闭 web 抢购通道。所以这个问题也不用兼容了，原地解散～
