### ISSUE TITLE
不能用。jd改了

### ISSUE THREAD

**Issue by 398907877** [abeelan/jdSeckill#4]
[ I 210201 11:06:35 seckill:225 ] 预约成功：https://www.jd.com/error2.aspx
[ I 210201 11:06:35 seckill:226 ] 预约成功，已获得抢购资格 / 您已成功预约过了，无需重复预约
[ I 210201 11:06:35 timer:65 ] 今天抢购时间已过，明天再来吧～
[ I 210201 11:06:35 seckill:239 ] 到达预设抢购时长，程序终止！

**Comment by 1181691792** [comment]
不会啊，我没出现你这个情况耶

**Comment by nbadao** [comment]
凉凉，2月1号起只能手机APP抢购了

**Comment by abeelan** [comment]
是的 客户端抢购限制更严格 原地解散～

**Comment by icycofee** [comment]
好像可以吧，接口还会返回90016错误
